version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-images:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/web/miniapp"
    schedule:
      interval: "weekly"
    groups:
      miniapp-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/web/admin"
    schedule:
      interval: "weekly"
    groups:
      admin-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/web/platform"
    schedule:
      interval: "weekly"
    groups:
      platform-dependencies:
        patterns:
          - "*"
