# syntax=docker/dockerfile:1

FROM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS build
WORKDIR /src

RUN apk add --no-cache ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY migrations ./migrations

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/api ./cmd/api

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
RUN apk add --no-cache ca-certificates tzdata ffmpeg 'giflib>=5.2.2-r2' 'libblkid>=2.41.6-r1' 'libmount>=2.41.6-r1' 'libcrypto3>=3.5.8-r0' 'libssl3>=3.5.8-r0' \
    && adduser -D -H -u 10001 appuser
WORKDIR /app

COPY --from=build /out/api /app/api
COPY --from=build /src/migrations /app/migrations

EXPOSE 8080
USER 10001
ENTRYPOINT ["/app/api"]
