# syntax=docker/dockerfile:1

FROM golang:1.27.0-alpine@sha256:4c9fe60190a2a3350ddc51de80d0224b8a6698d12bdfc999fee45ea9d6c46dbc AS build
WORKDIR /src

RUN apk add --no-cache ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY migrations ./migrations

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/api ./cmd/api

FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
RUN apk add --no-cache ca-certificates tzdata ffmpeg 'giflib>=5.2.2-r2' 'libblkid>=2.41.6-r1' 'libmount>=2.41.6-r1' 'libcrypto3>=3.5.8-r0' 'libssl3>=3.5.8-r0' \
    && adduser -D -H -u 10001 appuser
WORKDIR /app

COPY --from=build /out/api /app/api
COPY --from=build /src/migrations /app/migrations

EXPOSE 8080
USER 10001
ENTRYPOINT ["/app/api"]
