// Package worker contains the worker pools that turn queued Jobs into delivered
// results. Workers are the ONLY place AI providers are called (architecture
// invariant: VK handlers and the orchestrator never touch providers).
//
// Generation workers run the flow Job -> Provider -> ProviderTask -> Artifact ->
// Delivery Queue. When a provider is asynchronous the work is handed to the
// provider-poll worker (Provider Poll -> Update Status -> Requeue -> Artifact ->
// Delivery Queue). Every worker is retry-safe and idempotent: re-delivering the
// same task never double-submits to a provider or duplicates artifacts, and
// in-flight work is recovered after a restart via the consumer group's pending
// list.
package worker

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/attribute"

	redisqueue "vk-ai-aggregator/internal/adapter/queue/redis"
	"vk-ai-aggregator/internal/domain"
	"vk-ai-aggregator/internal/platform/metrics"
	"vk-ai-aggregator/internal/platform/queue"
	"vk-ai-aggregator/internal/platform/ratelimit"
	"vk-ai-aggregator/internal/platform/tracing"
	"vk-ai-aggregator/internal/service/dialogcontext"
	"vk-ai-aggregator/internal/service/moderationservice"
)

// maxProviderAttempts caps how many times a job is re-submitted to a provider
// before a retryable failure is treated as terminal.
const maxProviderAttempts = 3

// defaultProviderCallTimeout bounds one provider Submit/Poll call inside the
// worker so a stuck provider cannot keep a job generating forever.
const defaultProviderCallTimeout = 60 * time.Second

const (
	videoTranscodePolicyNever    = "never"
	videoTranscodePolicyFallback = "fallback"
	videoTranscodePolicyAlways   = "always"

	rawProviderVideoPolicyNever         = "never"
	rawProviderVideoPolicyIfProbePassed = "if_probe_passed"
	rawProviderVideoPolicyAlwaysDevOnly = "always_dev_only"
)

// ArtifactSaver stores provider outputs as artifacts. Implemented by
// artifactservice.Service.
type ArtifactSaver interface {
	SaveRemoteArtifact(ctx context.Context, ownerID uuid.UUID, jobID *uuid.UUID, kind domain.ArtifactKind, mediaType domain.MediaType, url string) (*domain.Artifact, error)
	SaveVariantWithMetadata(ctx context.Context, artifact *domain.Artifact, variantType domain.VariantType, mimeType string, data []byte, metadata domain.ArtifactMediaMetadata) (*domain.ArtifactVariant, error)
}

// VideoProber validates generated video bytes before delivery/capture.
type VideoProber interface {
	ProbeVideo(ctx context.Context, data []byte, sizeBytes int64) (domain.ArtifactMediaMetadata, error)
}

// VideoTranscoder creates delivery-ready video variants from generated bytes.
type VideoTranscoder interface {
	TranscodeVKVideo(ctx context.Context, data []byte, metadata domain.ArtifactMediaMetadata) ([]byte, domain.ArtifactMediaMetadata, error)
}

// StreamPublisher publishes a task to a specific stream. Implemented by
// redisqueue.Publisher.
type StreamPublisher interface {
	PublishTo(ctx context.Context, stream string, task queue.Task) error
}

// classedError is implemented by provider errors that carry a normalized class.
type classedError interface {
	ProviderErrorClass() domain.ProviderErrorClass
}

// Registry resolves which provider handles a request, and looks providers up
// by name when reconciling persisted provider tasks. Selection prefers healthy
// capable providers with lower configured cost and observed latency, then falls
// back across the chain when retryable submit failures occur.
type Registry struct {
	mu                  sync.Mutex
	byName              map[domain.ProviderName]domain.Provider
	order               []domain.ProviderName
	preferredByModality map[domain.Modality]domain.ProviderName
	breakers            map[domain.ProviderName]*breakerState
	mediaContracts      mediaContractRegistry
	mediaProviderBudget providerSubmitBudget
	quality             map[qualityKey]*qualityState
	qualityPolicy       providerQualityPolicy
	now                 func() time.Time
}

type providerSubmitBudget struct {
	configured          bool
	maxProviderAttempts int
	maxFallbackAttempts int
}

type providerQualityPolicy struct {
	enabled           bool
	degradedFailures  int
	disabledFailures  int
	recoverySuccesses int
}

type providerQualityStatus string

const (
	providerQualityHealthy  providerQualityStatus = "healthy"
	providerQualityDegraded providerQualityStatus = "degraded"
	providerQualityDisabled providerQualityStatus = "disabled"
)

type qualityKey struct {
	provider   domain.ProviderName
	modelClass string
	modality   domain.Modality
}

type qualityState struct {
	status              providerQualityStatus
	consecutiveFailures int
	consecutiveSuccess  int
	lastReason          string
	updatedAt           time.Time
}

// NewRegistry builds a registry with a default provider and optional extras.
func NewRegistry(def domain.Provider, more ...domain.Provider) *Registry {
	r := &Registry{
		byName:              map[domain.ProviderName]domain.Provider{},
		preferredByModality: map[domain.Modality]domain.ProviderName{},
		breakers:            map[domain.ProviderName]*breakerState{},
		quality:             map[qualityKey]*qualityState{},
		now:                 time.Now,
	}
	if def != nil {
		r.add(def)
	}
	for _, p := range more {
		r.add(p)
	}
	return r
}

// ConfigureProviderMediaContracts installs the worker-owned product allowlist
// used to reject risky video provider/model combinations before Submit.
func (r *Registry) ConfigureProviderMediaContracts(contracts []domain.ProviderMediaContract, requireVideoProbe, videoTranscodeEnabled bool) {
	if r == nil {
		return
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	r.mediaContracts = newMediaContractRegistry(contracts, requireVideoProbe, videoTranscodeEnabled)
}

// ConfigureMediaProviderBudget installs a global media submit budget. It is a
// second guard alongside per-model contracts and keeps paid media retries
// bounded even when future provider chains are configured.
func (r *Registry) ConfigureMediaProviderBudget(maxProviderAttempts, maxFallbackAttempts int) {
	if r == nil {
		return
	}
	if maxProviderAttempts < 0 {
		maxProviderAttempts = 0
	}
	if maxFallbackAttempts < 0 {
		maxFallbackAttempts = 0
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	r.mediaProviderBudget = providerSubmitBudget{
		configured:          true,
		maxProviderAttempts: maxProviderAttempts,
		maxFallbackAttempts: maxFallbackAttempts,
	}
}

// ConfigureProviderQualityGuard enables runtime routing decisions based on
// bounded provider/model_class/modality quality state. Disabled by default; even
// when enabled, the router will not drop all candidates at once.
func (r *Registry) ConfigureProviderQualityGuard(enabled bool, degradedFailures, disabledFailures, recoverySuccesses int) {
	if r == nil {
		return
	}
	if degradedFailures <= 0 {
		degradedFailures = 3
	}
	if disabledFailures < degradedFailures {
		disabledFailures = degradedFailures
	}
	if recoverySuccesses <= 0 {
		recoverySuccesses = 2
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	r.qualityPolicy = providerQualityPolicy{
		enabled:           enabled,
		degradedFailures:  degradedFailures,
		disabledFailures:  disabledFailures,
		recoverySuccesses: recoverySuccesses,
	}
}

// PreferProvider makes a provider the first candidate for a modality when it
// supports the request. Other capable providers remain explicit fallbacks.
func (r *Registry) PreferProvider(modality domain.Modality, name domain.ProviderName) {
	if modality == "" || name == "" {
		return
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	r.preferredByModality[modality] = name
}

func (r *Registry) add(p domain.Provider) {
	name := p.Name()
	if _, exists := r.byName[name]; !exists {
		r.order = append(r.order, name)
	}
	r.byName[name] = p
	if _, exists := r.breakers[name]; !exists {
		r.breakers[name] = &breakerState{}
	}
}

// ForOperation returns the provider that should handle an operation. It is kept
// for old callers/tests; new generation flow uses ForRequest so the router can
// account for modality and cost.
func (r *Registry) ForOperation(_ domain.OperationType) (domain.Provider, error) {
	if len(r.order) == 0 {
		return nil, errors.New("worker: no default provider configured")
	}
	return r.ForName(r.order[0])
}

// ForRequest returns a routed provider wrapper. Submit on the wrapper tries the
// selected provider chain in order and returns the task from the actual provider
// that accepted the request.
func (r *Registry) ForRequest(ctx context.Context, req domain.ProviderRequest) (domain.Provider, error) {
	candidates, err := r.candidates(ctx, req)
	if err != nil {
		return nil, err
	}
	return &routedProvider{registry: r, candidates: candidates}, nil
}

// ForName returns the provider with the given name.
func (r *Registry) ForName(name domain.ProviderName) (domain.Provider, error) {
	p, err := r.rawForName(name)
	if err != nil {
		return nil, err
	}
	return &observedProvider{registry: r, provider: p}, nil
}

func (r *Registry) rawForName(name domain.ProviderName) (domain.Provider, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	p, ok := r.byName[name]
	if !ok {
		return nil, fmt.Errorf("worker: unknown provider %q", name)
	}
	return p, nil
}

func (r *Registry) validateProviderMediaContract(provider domain.ProviderName, req domain.ProviderRequest, estimate domain.CostEstimate) (*domain.ProviderMediaContract, error) {
	if r == nil {
		return nil, nil
	}
	r.mu.Lock()
	contracts := r.mediaContracts
	r.mu.Unlock()
	return contracts.validateProviderSubmit(provider, req, estimate)
}

func (r *Registry) metricModelForRequest(provider domain.ProviderName, req domain.ProviderRequest, models ...string) string {
	if r == nil {
		return providerMetricModel(append(models, req.ModelCode)...)
	}
	r.mu.Lock()
	contracts := r.mediaContracts
	r.mu.Unlock()
	if class := contracts.modelClass(provider, req.ModelCode, req.Modality); class != "" {
		return providerMetricModel(class)
	}
	for _, model := range models {
		if class := contracts.modelClass(provider, model, req.Modality); class != "" {
			return providerMetricModel(class)
		}
	}
	return providerMetricModel(append(models, req.ModelCode)...)
}

func (r *Registry) qualityModelClassForRequest(provider domain.ProviderName, req domain.ProviderRequest, models ...string) string {
	if r == nil {
		return "default"
	}
	r.mu.Lock()
	contracts := r.mediaContracts
	r.mu.Unlock()
	if class := contracts.modelClass(provider, req.ModelCode, req.Modality); class != "" {
		return providerMetricModel(class)
	}
	for _, model := range models {
		if class := contracts.modelClass(provider, model, req.Modality); class != "" {
			return providerMetricModel(class)
		}
	}
	return "default"
}

func (r *Registry) metricModelForTask(provider domain.ProviderName, model string, modality domain.Modality) string {
	if r == nil {
		return providerMetricModel(model)
	}
	r.mu.Lock()
	contracts := r.mediaContracts
	r.mu.Unlock()
	if class := contracts.modelClass(provider, model, modality); class != "" {
		return providerMetricModel(class)
	}
	return providerMetricModel(model)
}

func (r *Registry) qualityModelClassForTask(provider domain.ProviderName, model string, modality domain.Modality) string {
	if r == nil {
		return "default"
	}
	r.mu.Lock()
	contracts := r.mediaContracts
	r.mu.Unlock()
	if class := contracts.modelClass(provider, model, modality); class != "" {
		return providerMetricModel(class)
	}
	return "default"
}

func (r *Registry) videoContractForTask(provider domain.ProviderName, model string) (*domain.ProviderMediaContract, bool) {
	if r == nil {
		return nil, false
	}
	r.mu.Lock()
	contracts := r.mediaContracts
	r.mu.Unlock()
	return contracts.videoContract(provider, model)
}

func qualityModelClassForRequest(contracts mediaContractRegistry, provider domain.ProviderName, req domain.ProviderRequest) string {
	if class := contracts.modelClass(provider, req.ModelCode, req.Modality); class != "" {
		return providerMetricModel(class)
	}
	return "default"
}

func (r *Registry) mediaProviderBudgetFor(req domain.ProviderRequest) (providerSubmitBudget, bool) {
	if r == nil || !isMediaProviderBudgetedRequest(req) {
		return providerSubmitBudget{}, false
	}
	r.mu.Lock()
	budget := r.mediaProviderBudget
	r.mu.Unlock()
	return budget, budget.configured
}

func isMediaProviderBudgetedRequest(req domain.ProviderRequest) bool {
	return req.Operation == domain.OperationVideoGenerate || req.Modality == domain.ModalityVideo
}

type providerCandidate struct {
	provider   domain.Provider
	name       domain.ProviderName
	modelClass string
	cost       int64
	latency    time.Duration
	open       bool
	quality    providerQualityStatus
	preferred  bool
	order      int
}

type breakerState struct {
	failures    int
	openedUntil time.Time
	latency     time.Duration
}

func (r *Registry) candidates(ctx context.Context, req domain.ProviderRequest) ([]providerCandidate, error) {
	r.mu.Lock()
	order := append([]domain.ProviderName(nil), r.order...)
	providers := make(map[domain.ProviderName]domain.Provider, len(r.byName))
	states := make(map[domain.ProviderName]breakerState, len(r.breakers))
	qualityStates := make(map[qualityKey]qualityState, len(r.quality))
	qualityPolicy := r.qualityPolicy
	contracts := r.mediaContracts
	preferred := r.preferredByModality[req.Modality]
	now := r.now()
	for name, provider := range r.byName {
		providers[name] = provider
	}
	for name, state := range r.breakers {
		states[name] = *state
	}
	for key, state := range r.quality {
		qualityStates[key] = *state
	}
	r.mu.Unlock()

	var healthy []providerCandidate
	var degraded []providerCandidate
	var disabled []providerCandidate
	var open []providerCandidate
	for idx, name := range order {
		provider := providers[name]
		if provider == nil {
			continue
		}
		if ok, err := supports(ctx, provider, req); err != nil || !ok {
			continue
		}
		estimate, err := provider.Estimate(ctx, req)
		if err != nil {
			if classOf(err) == domain.ProviderErrUnsupportedCapab {
				continue
			}
			estimate.AmountCredits = int64(idx + 1)
		}
		modelClass := qualityModelClassForRequest(contracts, name, req)
		quality := providerQualityHealthy
		if state, ok := qualityStates[qualityKey{provider: name, modelClass: modelClass, modality: req.Modality}]; ok && state.status != "" {
			quality = state.status
		}
		st := states[name]
		candidate := providerCandidate{
			provider:   provider,
			name:       name,
			modelClass: modelClass,
			cost:       estimate.AmountCredits,
			latency:    st.latency,
			open:       !st.openedUntil.IsZero() && now.Before(st.openedUntil),
			quality:    quality,
			preferred:  preferred != "" && name == preferred,
			order:      idx,
		}
		if qualityPolicy.enabled && candidate.quality == providerQualityDisabled {
			disabled = append(disabled, candidate)
			continue
		}
		if candidate.open {
			open = append(open, candidate)
			continue
		}
		if qualityPolicy.enabled && candidate.quality == providerQualityDegraded {
			degraded = append(degraded, candidate)
			continue
		}
		healthy = append(healthy, candidate)
	}
	sortCandidates(healthy)
	if len(healthy) > 0 {
		return healthy, nil
	}
	sortCandidates(degraded)
	if len(degraded) > 0 {
		return degraded, nil
	}
	sortCandidates(open)
	if len(open) > 0 {
		// All capable providers are open. Try them anyway so a temporary breaker
		// window cannot make the platform permanently unavailable.
		return open, nil
	}
	sortCandidates(disabled)
	if len(disabled) > 0 {
		// Do not auto-disable the whole product path. If every capable provider
		// is disabled, try the least risky candidate so the job can fail through
		// normal retry/release paths instead of a permanent routing outage.
		return disabled, nil
	}
	return nil, fmt.Errorf("worker: no provider supports %s/%s", req.Operation, req.Modality)
}

func sortCandidates(c []providerCandidate) {
	sort.SliceStable(c, func(i, j int) bool {
		if c[i].preferred != c[j].preferred {
			return c[i].preferred
		}
		if c[i].cost != c[j].cost {
			return c[i].cost < c[j].cost
		}
		if c[i].latency != c[j].latency {
			if c[i].latency == 0 {
				return false
			}
			if c[j].latency == 0 {
				return true
			}
			return c[i].latency < c[j].latency
		}
		return c[i].order < c[j].order
	})
}

func supports(ctx context.Context, provider domain.Provider, req domain.ProviderRequest) (bool, error) {
	caps, err := provider.Capabilities(ctx)
	if err != nil {
		return false, err
	}
	for _, cap := range caps {
		if cap.Operation != req.Operation {
			continue
		}
		if cap.Modality != "" && req.Modality != "" && cap.Modality != req.Modality {
			continue
		}
		if req.ModelCode != "" && cap.ModelCode != "" && req.ModelCode != cap.ModelCode {
			continue
		}
		return true, nil
	}
	return false, nil
}

func (r *Registry) record(name domain.ProviderName, started time.Time, err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	state := r.breakers[name]
	if state == nil {
		state = &breakerState{}
		r.breakers[name] = state
	}
	if !started.IsZero() {
		elapsed := r.now().Sub(started)
		if elapsed > 0 {
			if state.latency == 0 {
				state.latency = elapsed
			} else {
				state.latency = (state.latency + elapsed) / 2
			}
		}
	}
	if err == nil {
		state.failures = 0
		state.openedUntil = time.Time{}
		metrics.ProviderCircuitState.WithLabelValues(string(name), "all").Set(0)
		return
	}
	if !isRetryable(classOf(err)) {
		metrics.ProviderCircuitState.WithLabelValues(string(name), "all").Set(0)
		return
	}
	state.failures++
	if state.failures >= 2 {
		state.openedUntil = r.now().Add(time.Duration(state.failures) * 30 * time.Second)
	}
	open := 0.0
	if !state.openedUntil.IsZero() && r.now().Before(state.openedUntil) {
		open = 1
	}
	metrics.ProviderCircuitState.WithLabelValues(string(name), "all").Set(open)
}

func (r *Registry) recordProviderQualitySuccess(provider domain.ProviderName, model string, modality domain.Modality) {
	if r == nil {
		return
	}
	r.updateProviderQuality(provider, r.qualityModelClassForTask(provider, model, modality), modality, "", true)
}

func (r *Registry) recordProviderQualityFailure(provider domain.ProviderName, model string, modality domain.Modality, reason string) {
	if r == nil {
		return
	}
	r.updateProviderQuality(provider, r.qualityModelClassForTask(provider, model, modality), modality, reason, false)
}

func (r *Registry) recordProviderQualityForRequest(provider domain.ProviderName, req domain.ProviderRequest, model string, err error) {
	if r == nil {
		return
	}
	modelClass := r.qualityModelClassForRequest(provider, req, model)
	if err == nil {
		r.updateProviderQuality(provider, modelClass, req.Modality, "", true)
		return
	}
	reason := "provider_error"
	if class := classOf(err); class != "" {
		reason = string(class)
	}
	r.updateProviderQuality(provider, modelClass, req.Modality, reason, false)
}

func (r *Registry) updateProviderQuality(provider domain.ProviderName, modelClass string, modality domain.Modality, reason string, success bool) {
	if r == nil {
		return
	}
	if modelClass == "" {
		modelClass = "default"
	}
	if reason == "" {
		reason = "none"
	}
	now := r.now()
	r.mu.Lock()
	if r.quality == nil {
		r.quality = map[qualityKey]*qualityState{}
	}
	policy := r.qualityPolicy
	key := qualityKey{provider: provider, modelClass: providerMetricModel(modelClass), modality: modality}
	state := r.quality[key]
	if state == nil {
		state = &qualityState{status: providerQualityHealthy}
		r.quality[key] = state
	}
	if success {
		state.consecutiveFailures = 0
		state.consecutiveSuccess++
		state.lastReason = "none"
		if state.status != providerQualityHealthy && (!policy.enabled || state.consecutiveSuccess >= policy.recoverySuccesses) {
			state.status = providerQualityHealthy
		}
	} else {
		state.consecutiveSuccess = 0
		state.consecutiveFailures++
		state.lastReason = reason
		if policy.enabled {
			switch {
			case state.consecutiveFailures >= policy.disabledFailures:
				state.status = providerQualityDisabled
			case state.consecutiveFailures >= policy.degradedFailures:
				state.status = providerQualityDegraded
			}
		} else if state.consecutiveFailures >= 1 {
			state.status = providerQualityDegraded
		}
	}
	state.updatedAt = now
	status := state.status
	r.mu.Unlock()

	result := "failure"
	if success {
		result = "success"
	}
	metrics.ObserveProviderQualitySample(string(provider), key.modelClass, string(modality), result)
	metrics.ObserveProviderQualityState(string(provider), key.modelClass, string(modality), string(status))
}

type observedProvider struct {
	registry *Registry
	provider domain.Provider
}

func (p *observedProvider) Name() domain.ProviderName { return p.provider.Name() }
func (p *observedProvider) Capabilities(ctx context.Context) ([]domain.Capability, error) {
	return p.provider.Capabilities(ctx)
}
func (p *observedProvider) Estimate(ctx context.Context, req domain.ProviderRequest) (domain.CostEstimate, error) {
	return p.provider.Estimate(ctx, req)
}
func (p *observedProvider) Submit(ctx context.Context, req domain.ProviderRequest) (domain.ProviderTask, error) {
	estimate, _ := p.provider.Estimate(ctx, req)
	if _, err := p.registry.validateProviderMediaContract(p.provider.Name(), req, estimate); err != nil {
		return domain.ProviderTask{}, err
	}
	started := p.registry.now()
	task, err := p.provider.Submit(ctx, req)
	p.registry.record(p.provider.Name(), started, err)
	recordProviderCall(p.provider.Name(), p.registry.metricModelForRequest(p.provider.Name(), req, task.ModelCode), req.Operation, started, err, "")
	p.registry.recordProviderQualityForRequest(p.provider.Name(), req, task.ModelCode, err)
	return task, err
}
func (p *observedProvider) Poll(ctx context.Context, ref domain.ProviderTaskRef) (domain.ProviderTaskResult, error) {
	started := p.registry.now()
	res, err := p.provider.Poll(ctx, ref)
	recordErr := err
	if err == nil && res.Status == domain.ProviderTaskFailed && isRetryable(res.ErrorClass) {
		recordErr = providerResultError{class: res.ErrorClass, message: res.ErrorMessage}
	}
	p.registry.record(p.provider.Name(), started, recordErr)
	return res, err
}
func (p *observedProvider) Cancel(ctx context.Context, ref domain.ProviderTaskRef) error {
	started := p.registry.now()
	err := p.provider.Cancel(ctx, ref)
	p.registry.record(p.provider.Name(), started, err)
	return err
}

type routedProvider struct {
	registry   *Registry
	candidates []providerCandidate
}

func (p *routedProvider) Name() domain.ProviderName {
	if len(p.candidates) == 0 {
		return ""
	}
	return p.candidates[0].name
}
func (p *routedProvider) Capabilities(ctx context.Context) ([]domain.Capability, error) {
	if len(p.candidates) == 0 {
		return nil, errors.New("worker: no routed provider candidates")
	}
	return p.candidates[0].provider.Capabilities(ctx)
}
func (p *routedProvider) Estimate(ctx context.Context, req domain.ProviderRequest) (domain.CostEstimate, error) {
	if len(p.candidates) == 0 {
		return domain.CostEstimate{}, errors.New("worker: no routed provider candidates")
	}
	return p.candidates[0].provider.Estimate(ctx, req)
}
func (p *routedProvider) Submit(ctx context.Context, req domain.ProviderRequest) (domain.ProviderTask, error) {
	var last error
	submittedAttempts := 0
	fallbackAttempts := 0
	budget, budgeted := p.registry.mediaProviderBudgetFor(req)
	for idx, candidate := range p.candidates {
		contract, err := p.registry.validateProviderMediaContract(candidate.name, req, domain.CostEstimate{AmountCredits: candidate.cost, Currency: "credits"})
		if err != nil {
			last = err
			continue
		}
		started := p.registry.now()
		task, err := candidate.provider.Submit(ctx, req)
		p.registry.record(candidate.name, started, err)
		recordProviderCall(candidate.name, p.registry.metricModelForRequest(candidate.name, req, task.ModelCode), req.Operation, started, err, "")
		p.registry.recordProviderQualityForRequest(candidate.name, req, task.ModelCode, err)
		submittedAttempts++
		if err == nil {
			if task.Provider == "" {
				task.Provider = candidate.name
			}
			if candidate.cost > 0 {
				model := p.registry.metricModelForRequest(candidate.name, req, task.ModelCode)
				metrics.ProviderEstimatedCost.WithLabelValues(string(candidate.name), model, operationMetricLabel(req.Operation), "credits").Add(float64(candidate.cost))
			}
			return task, nil
		}
		last = err
		if !isFallbackError(err) {
			break
		}
		if budgeted && budget.maxProviderAttempts > 0 && submittedAttempts >= budget.maxProviderAttempts {
			metrics.ProviderFallback.WithLabelValues(
				string(candidate.name),
				"none",
				operationMetricLabel(req.Operation),
				"media_attempt_budget_exhausted",
			).Inc()
			break
		}
		if contract != nil && contract.MaxProviderAttempts > 0 && submittedAttempts >= contract.MaxProviderAttempts {
			metrics.ProviderFallback.WithLabelValues(
				string(candidate.name),
				"none",
				operationMetricLabel(req.Operation),
				"contract_attempt_budget_exhausted",
			).Inc()
			break
		}
		hasNext := idx+1 < len(p.candidates)
		if hasNext && budgeted && fallbackAttempts >= budget.maxFallbackAttempts {
			metrics.ProviderFallback.WithLabelValues(
				string(candidate.name),
				"none",
				operationMetricLabel(req.Operation),
				"media_fallback_budget_exhausted",
			).Inc()
			break
		}
		if hasNext && contract != nil && fallbackAttempts >= contract.MaxFallbackAttempts {
			metrics.ProviderFallback.WithLabelValues(
				string(candidate.name),
				"none",
				operationMetricLabel(req.Operation),
				"contract_budget_exhausted",
			).Inc()
			break
		}
		if hasNext {
			fallbackAttempts++
			metrics.ProviderFallback.WithLabelValues(
				string(candidate.name),
				string(p.candidates[idx+1].name),
				operationMetricLabel(req.Operation),
				string(classOf(err)),
			).Inc()
		} else {
			metrics.ProviderFallback.WithLabelValues(
				string(candidate.name),
				"none",
				operationMetricLabel(req.Operation),
				"exhausted",
			).Inc()
		}
	}
	if last == nil {
		last = errors.New("worker: no routed provider candidates")
	}
	return domain.ProviderTask{}, last
}
func (p *routedProvider) Poll(ctx context.Context, ref domain.ProviderTaskRef) (domain.ProviderTaskResult, error) {
	provider, err := p.registry.ForName(ref.Provider)
	if err != nil {
		return domain.ProviderTaskResult{}, err
	}
	return provider.Poll(ctx, ref)
}
func (p *routedProvider) Cancel(ctx context.Context, ref domain.ProviderTaskRef) error {
	provider, err := p.registry.ForName(ref.Provider)
	if err != nil {
		return err
	}
	return provider.Cancel(ctx, ref)
}

func isFallbackError(err error) bool {
	class := classOf(err)
	return isRetryable(class) || class == domain.ProviderErrUnsupportedCapab
}

type providerResultError struct {
	class   domain.ProviderErrorClass
	message string
}

func (e providerResultError) Error() string {
	if e.message != "" {
		return e.message
	}
	return string(e.class)
}

func (e providerResultError) ProviderErrorClass() domain.ProviderErrorClass { return e.class }

// processor holds the shared dependencies and result-handling logic used by
// both the generation and poll workers.
type processor struct {
	jobs                 domain.JobRepository
	tasks                domain.ProviderTaskRepository
	artifacts            ArtifactSaver
	artifactRepo         domain.ArtifactRepository
	objects              ObjectStore
	providers            *Registry
	streams              StreamPublisher
	imageModel           string
	imageSize            string
	videoModel           string
	videoDurationSec     int
	videoResolution      string
	videoAspectRatio     string
	videoDraft           bool
	videoProber          VideoProber
	videoTranscoder      VideoTranscoder
	requireVideoProbe    bool
	videoTranscodePolicy string
	rawVideoPolicy       string
	probeLimiter         *ratelimit.ConcurrencyLimiter
	transcodeLimiter     *ratelimit.ConcurrencyLimiter
	variantLimiter       *ratelimit.ConcurrencyLimiter
	textContext          TextContext
	moderator            Moderator
	modResults           domain.ModerationResultRepository
	releaser             ReservationReleaser
	maxAttempts          int
	backoff              func(attempt int) time.Duration
	callTimeout          time.Duration
	now                  func() time.Time
}

// Moderator gates delivery: generated output must pass a moderation check
// before it is delivered (invariant #15). Implemented by moderationservice.
type Moderator interface {
	Name() string
	Check(ctx context.Context, in moderationservice.Input) (moderationservice.Outcome, error)
}

// ReservationReleaser frees a job's reserved credits when delivery is blocked
// (e.g. by moderation) so blocked jobs are never charged. Implemented by
// billingservice.Service.
type ReservationReleaser interface {
	ReleaseForJob(ctx context.Context, jobID uuid.UUID) error
}

// TextContext prepares compact dialog context for text jobs and records
// assistant answers after provider success.
type TextContext interface {
	Prepare(ctx context.Context, job *domain.Job, prompt string) (dialogcontext.Prepared, error)
	Complete(ctx context.Context, job *domain.Job, conversationID uuid.UUID, answer string) error
}

// Deps bundles the dependencies shared by the workers.
type Deps struct {
	Jobs      domain.JobRepository
	Tasks     domain.ProviderTaskRepository
	Artifacts ArtifactSaver
	// ArtifactRepo loads input artifact metadata for provider request assembly.
	ArtifactRepo domain.ArtifactRepository
	// Objects loads input artifact bytes for provider request assembly.
	Objects   ObjectStore
	Providers *Registry
	Streams   StreamPublisher
	// ImageModel/ImageSize are optional product-level defaults for image jobs.
	// They are translated into the provider request only inside workers.
	ImageModel string
	ImageSize  string
	// VideoModel and related fields are worker-owned defaults for video jobs.
	VideoModel       string
	VideoDurationSec int
	VideoResolution  string
	VideoAspectRatio string
	VideoDraft       bool
	// VideoProber, when set, validates generated videos before delivery/capture.
	VideoProber VideoProber
	// VideoTranscoder, when set, creates VK-ready video variants after probing.
	VideoTranscoder VideoTranscoder
	// RequireVideoProbe makes video jobs fail closed when no prober is configured.
	RequireVideoProbe bool
	// VideoTranscodeEnabled reports whether worker policy allows expensive video
	// transcode work. Provider media contracts use it before Submit.
	VideoTranscodeEnabled bool
	// VideoTranscodePolicy controls whether ffmpeg is allowed for unsafe video
	// outputs. Values mirror config: never, fallback, always.
	VideoTranscodePolicy string
	// RawVideoDeliveryPolicy controls whether a probed delivery-ready original
	// may be delivered without a VK-specific variant.
	RawVideoDeliveryPolicy string
	// ProviderMediaContracts is the product-level allowlist for risky video
	// provider/model combinations.
	ProviderMediaContracts []domain.ProviderMediaContract
	// MediaMaxConcurrentProbes and MediaMaxConcurrentTranscodes bound CPU-heavy
	// media work per worker process. Shared queue/user capacity is handled
	// before job creation by the API/orchestrator.
	MediaMaxConcurrentProbes              int
	MediaMaxConcurrentTranscodes          int
	MediaMaxPendingVariants               int
	MediaProviderMaxAttempts              int
	MediaProviderFallbackBudget           int
	MediaProviderQualityGuardEnabled      bool
	MediaProviderQualityDegradedFailures  int
	MediaProviderQualityDisabledFailures  int
	MediaProviderQualityRecoverySuccesses int
	// TextContext, when set, stores VK text dialog history and renders compact
	// provider prompts for text jobs.
	TextContext TextContext
	// Moderator, when set, runs an output moderation check before delivery.
	// When nil, moderation is skipped (allow-all) for local/test wiring.
	Moderator Moderator
	// ModResults, when set, persists moderation verdicts for audit.
	ModResults domain.ModerationResultRepository
	// Releaser, when set, frees reserved credits for moderation-blocked jobs
	// and terminal provider failures before capture.
	Releaser ReservationReleaser
	// MaxAttempts caps retryable re-enqueues before dead-lettering (default 3).
	MaxAttempts int
	// Backoff returns the delay before re-enqueue for the given attempt number.
	// Defaults to no delay (keeps tests fast).
	Backoff func(attempt int) time.Duration
	// ProviderCallTimeout bounds one provider Submit/Poll call (default 60s).
	ProviderCallTimeout time.Duration
	// Now overrides the clock; defaults to time.Now.
	Now func() time.Time
}

func newProcessor(d Deps) processor {
	now := d.Now
	if now == nil {
		now = time.Now
	}
	maxAttempts := d.MaxAttempts
	if maxAttempts <= 0 {
		maxAttempts = maxProviderAttempts
	}
	backoff := d.Backoff
	if backoff == nil {
		backoff = func(int) time.Duration { return 0 }
	}
	callTimeout := d.ProviderCallTimeout
	if callTimeout <= 0 {
		callTimeout = defaultProviderCallTimeout
	}
	videoTranscodePolicy := normalizeWorkerPolicy(d.VideoTranscodePolicy)
	if videoTranscodePolicy == "" {
		if d.VideoTranscodeEnabled || d.VideoTranscoder != nil {
			videoTranscodePolicy = videoTranscodePolicyFallback
		} else {
			videoTranscodePolicy = videoTranscodePolicyNever
		}
	}
	rawVideoPolicy := normalizeWorkerPolicy(d.RawVideoDeliveryPolicy)
	if rawVideoPolicy == "" {
		rawVideoPolicy = rawProviderVideoPolicyAlwaysDevOnly
	}
	if d.Providers != nil {
		d.Providers.ConfigureProviderMediaContracts(d.ProviderMediaContracts, d.RequireVideoProbe, d.VideoTranscodeEnabled)
		if d.MediaProviderMaxAttempts > 0 || d.MediaProviderFallbackBudget > 0 {
			d.Providers.ConfigureMediaProviderBudget(d.MediaProviderMaxAttempts, d.MediaProviderFallbackBudget)
		}
		d.Providers.ConfigureProviderQualityGuard(
			d.MediaProviderQualityGuardEnabled,
			d.MediaProviderQualityDegradedFailures,
			d.MediaProviderQualityDisabledFailures,
			d.MediaProviderQualityRecoverySuccesses,
		)
	}
	return processor{
		jobs:                 d.Jobs,
		tasks:                d.Tasks,
		artifacts:            d.Artifacts,
		artifactRepo:         d.ArtifactRepo,
		objects:              d.Objects,
		providers:            d.Providers,
		streams:              d.Streams,
		imageModel:           d.ImageModel,
		imageSize:            d.ImageSize,
		videoModel:           d.VideoModel,
		videoDurationSec:     d.VideoDurationSec,
		videoResolution:      d.VideoResolution,
		videoAspectRatio:     d.VideoAspectRatio,
		videoDraft:           d.VideoDraft,
		videoProber:          d.VideoProber,
		videoTranscoder:      d.VideoTranscoder,
		requireVideoProbe:    d.RequireVideoProbe,
		videoTranscodePolicy: videoTranscodePolicy,
		rawVideoPolicy:       rawVideoPolicy,
		probeLimiter:         optionalConcurrencyLimiter(d.MediaMaxConcurrentProbes),
		transcodeLimiter:     optionalConcurrencyLimiter(d.MediaMaxConcurrentTranscodes),
		variantLimiter:       optionalConcurrencyLimiter(d.MediaMaxPendingVariants),
		textContext:          d.TextContext,
		moderator:            d.Moderator,
		modResults:           d.ModResults,
		releaser:             d.Releaser,
		maxAttempts:          maxAttempts,
		backoff:              backoff,
		callTimeout:          callTimeout,
		now:                  now,
	}
}

func optionalConcurrencyLimiter(limit int) *ratelimit.ConcurrencyLimiter {
	if limit <= 0 {
		return nil
	}
	return ratelimit.NewConcurrencyLimiter(limit)
}

func acquireOptionalLimiter(limiter *ratelimit.ConcurrencyLimiter) (func(), bool) {
	if limiter == nil {
		return func() {}, true
	}
	return limiter.TryAcquire()
}

func normalizeWorkerPolicy(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

// maxReferenceArtifacts must match miniapp/references.go limit.
const maxReferenceArtifacts = 4

const maxReferenceArtifactBytes = 20 << 20

// promptParams is the subset of job params the provider request needs.
type promptParams struct {
	Prompt                 string      `json:"prompt"`
	NegativePrompt         string      `json:"negative_prompt"`
	ModelCode              string      `json:"model_code,omitempty"`
	Size                   string      `json:"size,omitempty"`
	AspectRatio            string      `json:"aspect_ratio,omitempty"`
	ReferenceArtifactIDs   []uuid.UUID `json:"reference_artifact_ids,omitempty"`
	InputURLs              []string    `json:"input_urls,omitempty"`
	VKPlaceholderMessageID int64       `json:"vk_placeholder_message_id,omitempty"`
	ConversationID         string      `json:"conversation_id,omitempty"`
	ConversationSource     string      `json:"conversation_source,omitempty"`
	ExternalThreadID       string      `json:"external_thread_id,omitempty"`
	DurationSec            int         `json:"duration_sec,omitempty"`
}

// buildRequest builds the normalized provider request for a job. The submit
// idempotency key is scoped to the attempt so a re-delivered task maps to one
// provider task, while a genuine retry after failure starts a fresh one.
func (p *processor) buildRequest(ctx context.Context, job *domain.Job, attempt int) (domain.ProviderRequest, error) {
	var pp promptParams
	if len(job.Params) > 0 {
		_ = json.Unmarshal(job.Params, &pp)
	}
	prompt := pp.Prompt
	modelCode := pp.ModelCode
	size := pp.Size
	maxOutputTokens := 0
	durationSec := 0
	resolution := ""
	draft := false
	if job.Modality == domain.ModalityImage {
		if modelCode == "" {
			modelCode = p.imageModel
		}
		if size == "" {
			size = p.imageSize
		}
	}
	if job.Modality == domain.ModalityVideo {
		if modelCode == "" {
			modelCode = p.videoModel
		}
		durationSec = p.videoDurationSec
		if pp.DurationSec > 0 {
			durationSec = pp.DurationSec
		}
		resolution = p.videoResolution
		if pp.AspectRatio == "" {
			pp.AspectRatio = p.videoAspectRatio
		}
		draft = p.videoDraft
	}
	if p.textContext != nil && job.OperationType == domain.OperationTextGenerate && job.Modality == domain.ModalityText {
		prepared, err := p.textContext.Prepare(ctx, job, pp.Prompt)
		if err != nil {
			return domain.ProviderRequest{}, err
		}
		if prepared.Prompt != "" {
			prompt = prepared.Prompt
		}
		maxOutputTokens = prepared.MaxOutputTokens
		if prepared.ConversationID != uuid.Nil && pp.ConversationID != prepared.ConversationID.String() {
			pp.ConversationID = prepared.ConversationID.String()
			if raw, err := json.Marshal(pp); err == nil {
				job.Params = raw
				if err := p.jobs.Update(ctx, job); err != nil {
					return domain.ProviderRequest{}, err
				}
			}
		}
	}
	var inputURLs []string
	if job.Modality == domain.ModalityImage && len(pp.ReferenceArtifactIDs) > 0 {
		var err error
		inputURLs, err = p.resolveReferenceInputURLs(ctx, job, pp.ReferenceArtifactIDs)
		if err != nil {
			return domain.ProviderRequest{}, err
		}
	}
	providerParams := stripProviderInputURLs(job.Params)
	if job.Modality == domain.ModalityVideo {
		providerParams = safeVideoProviderParams(durationSec, resolution, pp.AspectRatio, draft)
	}
	return domain.ProviderRequest{
		JobID:                job.ID,
		UserID:               job.UserID,
		Operation:            job.OperationType,
		Modality:             job.Modality,
		ModelCode:            modelCode,
		Prompt:               prompt,
		NegativePrompt:       pp.NegativePrompt,
		Size:                 size,
		AspectRatio:          pp.AspectRatio,
		DurationSec:          durationSec,
		Resolution:           resolution,
		Draft:                draft,
		ReferenceArtifactIDs: pp.ReferenceArtifactIDs,
		InputURLs:            inputURLs,
		Params:               providerParams,
		MaxOutputTokens:      maxOutputTokens,
		IdempotencyKey:       fmt.Sprintf("provider_submit:%s:%d", job.ID, attempt),
		AttemptNo:            attempt,
	}, nil
}

func safeVideoProviderParams(durationSec int, resolution, aspectRatio string, draft bool) json.RawMessage {
	params := map[string]any{}
	if durationSec > 0 {
		params["duration_sec"] = durationSec
	}
	if strings.TrimSpace(resolution) != "" {
		params["resolution"] = strings.TrimSpace(resolution)
	}
	if strings.TrimSpace(aspectRatio) != "" {
		params["aspect_ratio"] = strings.TrimSpace(aspectRatio)
	}
	if draft {
		params["draft"] = true
	}
	raw, err := json.Marshal(params)
	if err != nil {
		return nil
	}
	return raw
}

func stripProviderInputURLs(raw json.RawMessage) json.RawMessage {
	if len(raw) == 0 {
		return raw
	}
	var params map[string]json.RawMessage
	if err := json.Unmarshal(raw, &params); err != nil {
		return raw
	}
	if _, ok := params["input_urls"]; !ok {
		return raw
	}
	delete(params, "input_urls")
	out, err := json.Marshal(params)
	if err != nil {
		return raw
	}
	return out
}

func (p *processor) resolveReferenceInputURLs(ctx context.Context, job *domain.Job, ids []uuid.UUID) ([]string, error) {
	if len(ids) > maxReferenceArtifacts {
		return nil, fmt.Errorf("worker: too many reference artifacts")
	}
	if p.artifactRepo == nil {
		return nil, fmt.Errorf("worker: artifact repository unavailable")
	}
	if p.objects == nil {
		return nil, fmt.Errorf("worker: object store unavailable")
	}
	inputURLs := make([]string, 0, len(ids))
	for _, id := range ids {
		if id == uuid.Nil {
			return nil, fmt.Errorf("worker: invalid reference artifact id")
		}
		artifact, err := p.artifactRepo.GetByID(ctx, id)
		if err != nil {
			return nil, fmt.Errorf("worker: reference artifact not found: %w", err)
		}
		if artifact.OwnerUserID != job.UserID {
			return nil, fmt.Errorf("worker: invalid reference artifact owner")
		}
		if artifact.Kind != domain.ArtifactKindInput || artifact.MediaType != domain.MediaTypeImage || artifact.Status != domain.ArtifactStatusReady {
			return nil, fmt.Errorf("worker: invalid reference artifact")
		}
		if artifact.StorageBucket == "" || artifact.StorageKey == "" {
			return nil, fmt.Errorf("worker: reference artifact storage missing")
		}
		data, err := p.objects.GetObject(ctx, artifact.StorageBucket, artifact.StorageKey)
		if err != nil {
			return nil, fmt.Errorf("worker: reference artifact object missing: %w", err)
		}
		if len(data) > maxReferenceArtifactBytes {
			return nil, fmt.Errorf("worker: reference artifact too large")
		}
		inputURL, err := sanitizedReferenceImageDataURL(data, artifact.MimeType)
		if err != nil {
			return nil, err
		}
		inputURLs = append(inputURLs, inputURL)
	}
	return inputURLs, nil
}

// taskOf builds the queue task that represents a job.
func taskOf(job *domain.Job) queue.Task {
	return queue.Task{
		JobID:         job.ID,
		Operation:     job.OperationType,
		Modality:      job.Modality,
		CorrelationID: job.CorrelationID,
	}
}

func mediaTypeFor(modality domain.Modality) domain.MediaType {
	switch modality {
	case domain.ModalityImage:
		return domain.MediaTypeImage
	case domain.ModalityVideo:
		return domain.MediaTypeVideo
	case domain.ModalityAudio:
		return domain.MediaTypeAudio
	default:
		return domain.MediaTypeText
	}
}

// isDone reports whether a job has reached a state where neither generation nor
// polling should act on it any further.
func isDone(status domain.JobStatus) bool {
	switch status {
	case domain.JobStatusResultReady,
		domain.JobStatusDelivering,
		domain.JobStatusSucceeded,
		domain.JobStatusFailedTerminal,
		domain.JobStatusCancelled,
		domain.JobStatusRefunded,
		domain.JobStatusRejected,
		domain.JobStatusExpired:
		return true
	default:
		return false
	}
}

// isRetryable maps a normalized provider error class to a retry decision.
func isRetryable(class domain.ProviderErrorClass) bool {
	switch class {
	case domain.ProviderErrRateLimited,
		domain.ProviderErrTimeout,
		domain.ProviderErrOverloaded,
		domain.ProviderErrInternal,
		domain.ProviderErrOutputDownloadFailed:
		return true
	default:
		return false
	}
}

// classOf extracts the normalized error class from a provider error, defaulting
// to provider_internal_error for unclassified failures.
func classOf(err error) domain.ProviderErrorClass {
	var ce classedError
	if errors.As(err, &ce) {
		return ce.ProviderErrorClass()
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return domain.ProviderErrTimeout
	}
	return domain.ProviderErrInternal
}

func recordProviderCall(provider domain.ProviderName, model string, operation domain.OperationType, started time.Time, err error, result string) {
	if result == "" {
		if err == nil {
			result = "success"
		} else {
			result = "error"
		}
	}
	providerLabel := providerMetricProvider(provider)
	modelLabel := providerMetricModel(model)
	operationLabel := operationMetricLabel(operation)
	metrics.ProviderRequests.WithLabelValues(providerLabel, modelLabel, operationLabel, result).Inc()
	if !started.IsZero() {
		duration := time.Since(started)
		if duration > 0 {
			metrics.ProviderRequestDuration.WithLabelValues(providerLabel, modelLabel, operationLabel).Observe(duration.Seconds())
		}
	}
	if err == nil {
		return
	}
	class := classOf(err)
	metrics.ProviderErrors.WithLabelValues(providerLabel, modelLabel, operationLabel, string(class)).Inc()
	if class == domain.ProviderErrRateLimited {
		metrics.ProviderRateLimits.WithLabelValues(providerLabel, modelLabel, operationLabel).Inc()
	}
}

func (p *processor) recordProviderPoll(provider domain.ProviderName, model string, modality domain.Modality, operation domain.OperationType, started time.Time, res domain.ProviderTaskResult, err error) {
	result := "success"
	if err != nil {
		result = "error"
	} else if res.Status != "" {
		result = string(res.Status)
	}
	modelLabel := providerMetricModel(model)
	if p.providers != nil {
		modelLabel = p.providers.metricModelForTask(provider, model, modality)
	}
	recordProviderCall(provider, modelLabel, operation, started, err, result)
	if err == nil && res.Status == domain.ProviderTaskFailed && res.ErrorClass != "" {
		providerLabel := providerMetricProvider(provider)
		operationLabel := operationMetricLabel(operation)
		metrics.ProviderErrors.WithLabelValues(providerLabel, modelLabel, operationLabel, string(res.ErrorClass)).Inc()
		if res.ErrorClass == domain.ProviderErrRateLimited {
			metrics.ProviderRateLimits.WithLabelValues(providerLabel, modelLabel, operationLabel).Inc()
		}
	}
	if p.providers == nil {
		return
	}
	switch {
	case err != nil:
		p.providers.recordProviderQualityFailure(provider, model, modality, string(classOf(err)))
	case res.Status == domain.ProviderTaskFailed && res.ErrorClass != "":
		p.providers.recordProviderQualityFailure(provider, model, modality, string(res.ErrorClass))
	case res.Status == domain.ProviderTaskSucceeded:
		p.providers.recordProviderQualitySuccess(provider, model, modality)
	}
}

func (p *processor) recordProviderOutputs(pt *domain.ProviderTask, job *domain.Job, res domain.ProviderTaskResult) {
	if pt == nil || job == nil {
		return
	}
	count := float64(len(res.OutputURLs))
	if count <= 0 {
		return
	}
	providerLabel := providerMetricProvider(pt.Provider)
	modelLabel := providerMetricModel(pt.ModelCode)
	if p.providers != nil {
		modelLabel = p.providers.metricModelForTask(pt.Provider, pt.ModelCode, job.Modality)
	}
	operationLabel := operationMetricLabel(job.OperationType)
	switch job.Modality {
	case domain.ModalityImage:
		metrics.ProviderImages.WithLabelValues(providerLabel, modelLabel, operationLabel).Add(count)
	case domain.ModalityVideo:
		metrics.ProviderVideos.WithLabelValues(providerLabel, modelLabel, operationLabel).Add(count)
	}
}

func (p *processor) recordProviderProductFailure(ctx context.Context, job *domain.Job, reason string) {
	if job == nil {
		return
	}
	task, err := p.latestTask(ctx, job.ID)
	if err != nil || task == nil {
		return
	}
	p.recordProviderProductFailureForTask(job, task, reason)
}

func (p *processor) recordProviderProductFailureForTask(job *domain.Job, task *domain.ProviderTask, reason string) {
	if p == nil || job == nil || task == nil {
		return
	}
	modelClass := "default"
	if p.providers != nil {
		modelClass = p.providers.qualityModelClassForTask(task.Provider, task.ModelCode, job.Modality)
		p.providers.recordProviderQualityFailure(task.Provider, task.ModelCode, job.Modality, reason)
	}
	metrics.ObserveProviderOutputInvalid(string(task.Provider), modelClass, string(job.Modality), reason)
	metrics.AddProductMediaWaste(string(task.Provider), modelClass, string(job.Modality), reason, job.CostReserved)
}

func providerMetricProvider(provider domain.ProviderName) string {
	if provider == "" {
		return "unknown"
	}
	return metricLabel(string(provider))
}

func providerMetricModel(models ...string) string {
	for _, model := range models {
		if trimmed := strings.TrimSpace(model); trimmed != "" {
			return metricLabel(trimmed)
		}
	}
	return "default"
}

func operationMetricLabel(operation domain.OperationType) string {
	if operation == "" {
		return "unknown"
	}
	return metricLabel(string(operation))
}

func modalityMetricLabel(modality domain.Modality) string {
	if modality == "" {
		return "unknown"
	}
	return metricLabel(string(modality))
}

func metricLabel(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	if value == "" {
		return "unknown"
	}
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_' || r == '-' || r == '.' || r == ':' || r == '/':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
		if b.Len() >= 96 {
			break
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "unknown"
	}
	return out
}

func (p *processor) providerCallContext(ctx context.Context) (context.Context, context.CancelFunc) {
	if p.callTimeout <= 0 {
		return ctx, func() {}
	}
	return context.WithTimeout(ctx, p.callTimeout)
}

// setStatus applies a state-machine transition, treating "already there" as a
// no-op so repeated deliveries are idempotent.
func (p *processor) setStatus(ctx context.Context, job *domain.Job, to domain.JobStatus, errCode, errMsg string) error {
	if job.Status == to {
		return nil
	}
	from := job.Status
	if err := p.jobs.UpdateStatus(ctx, job.ID, job.Status, to, errCode, errMsg); err != nil {
		return err
	}
	job.Status = to
	metrics.JobStatusCurrent.WithLabelValues(string(from), operationMetricLabel(job.OperationType), modalityMetricLabel(job.Modality)).Dec()
	metrics.JobStatusCurrent.WithLabelValues(string(to), operationMetricLabel(job.OperationType), modalityMetricLabel(job.Modality)).Inc()
	if to.IsTerminal() && !job.CreatedAt.IsZero() {
		duration := time.Since(job.CreatedAt)
		if duration > 0 {
			metrics.JobDuration.WithLabelValues(operationMetricLabel(job.OperationType), modalityMetricLabel(job.Modality), string(to)).Observe(duration.Seconds())
		}
	}
	if to == domain.JobStatusResultReady {
		metrics.ObserveProductEvent("worker", "job", "result_ready", operationMetricLabel(job.OperationType), modalityMetricLabel(job.Modality), "success")
	}
	if to.IsTerminal() {
		metrics.ObserveProductEvent("worker", "job", "terminal", operationMetricLabel(job.OperationType), modalityMetricLabel(job.Modality), string(to))
	}
	if to == domain.JobStatusRejected {
		reason := errCode
		if reason == "" {
			reason = "rejected"
		}
		metrics.JobRejected.WithLabelValues(metricLabel(reason), modalityMetricLabel(job.Modality)).Inc()
	}
	return nil
}

// activeTask returns the most recent provider task for a job that is still
// pending/processing/succeeded (i.e. worth polling), or nil if the job needs a
// fresh submission.
func (p *processor) activeTask(ctx context.Context, jobID uuid.UUID) (*domain.ProviderTask, error) {
	tasks, err := p.tasks.ListByJob(ctx, jobID)
	if err != nil {
		return nil, err
	}
	for i := len(tasks) - 1; i >= 0; i-- {
		switch tasks[i].Status {
		case domain.ProviderTaskPending, domain.ProviderTaskProcessing, domain.ProviderTaskSucceeded:
			return tasks[i], nil
		}
	}
	return nil, nil
}

// latestTask returns the most recent provider task for a job, or nil.
func (p *processor) latestTask(ctx context.Context, jobID uuid.UUID) (*domain.ProviderTask, error) {
	tasks, err := p.tasks.ListByJob(ctx, jobID)
	if err != nil || len(tasks) == 0 {
		return nil, err
	}
	return tasks[len(tasks)-1], nil
}

// pollOnce polls the provider once and applies the normalized result.
func (p *processor) pollOnce(ctx context.Context, job *domain.Job, pt *domain.ProviderTask, provider domain.Provider, task queue.Task) error {
	callCtx, cancel := p.providerCallContext(ctx)
	pollCtx, span := tracing.Start(callCtx, "provider.poll",
		attribute.String("job.id", job.ID.String()),
		attribute.String("provider", string(provider.Name())),
		attribute.String("provider.external_id", pt.ExternalID),
		tracing.CorrelationAttr(job.CorrelationID),
	)
	started := time.Now()
	res, err := provider.Poll(pollCtx, domain.ProviderTaskRef{Provider: pt.Provider, ExternalID: pt.ExternalID})
	p.recordProviderPoll(pt.Provider, pt.ModelCode, job.Modality, job.OperationType, started, res, err)
	if err != nil {
		tracing.RecordError(span, err)
		span.End()
		cancel()
		return p.handleFailure(ctx, job, task, classOf(err), err.Error())
	}
	span.SetAttributes(attribute.String("provider.task_status", string(res.Status)))
	span.End()
	cancel()
	return p.applyResult(ctx, job, pt, res, task)
}

// applyResult persists the task result and advances the job: success stores
// artifacts and enqueues delivery, in-progress requeues for polling, failure is
// classified and retried or made terminal.
func (p *processor) applyResult(ctx context.Context, job *domain.Job, pt *domain.ProviderTask, res domain.ProviderTaskResult, task queue.Task) error {
	pt.Status = res.Status
	if raw, err := json.Marshal(res); err == nil {
		pt.Result = raw
	}
	if res.ErrorClass != "" {
		pt.ErrorClass = res.ErrorClass
	}
	if res.Status.IsTerminal() {
		now := p.now()
		pt.CompletedAt = &now
	}
	if err := p.tasks.Update(ctx, pt); err != nil {
		return err
	}

	switch res.Status {
	case domain.ProviderTaskSucceeded:
		p.recordProviderOutputs(pt, job, res)
		if err := p.saveOutputs(ctx, job, res.OutputURLs); err != nil {
			p.recordProviderProductFailureForTask(job, pt, "output_download_failed")
			// A download failure is retryable provider-side.
			return p.handleFailure(ctx, job, task, domain.ProviderErrOutputDownloadFailed, err.Error())
		}
		if err := p.setStatus(ctx, job, domain.JobStatusProviderSucceeded, "", ""); err != nil {
			return err
		}
		if err := p.probeVideoOutputs(ctx, job); err != nil {
			var probeErr mediaProbeError
			var transcodeErr mediaTranscodeError
			switch {
			case errors.As(err, &probeErr):
				p.recordProviderProductFailure(ctx, job, string(probeErr))
				return p.handleMediaFailure(ctx, job, safeMediaFailureCode(err), safeMediaFailureMessage(err))
			case errors.As(err, &transcodeErr):
				p.recordProviderProductFailure(ctx, job, string(transcodeErr))
				return p.handleMediaFailure(ctx, job, safeMediaFailureCode(err), safeMediaFailureMessage(err))
			default:
				return err
			}
		}
		if err := p.saveDialogAnswer(ctx, job, res.Text); err != nil {
			slog.WarnContext(ctx, "dialog context answer save failed",
				slog.String("job_id", job.ID.String()),
				slog.String("error", err.Error()))
		}
		// Output moderation gates delivery (invariant #15). A block stops the
		// pipeline here: no delivery, no capture.
		blocked, err := p.moderateOutput(ctx, job)
		if err != nil {
			return err
		}
		if blocked {
			return nil
		}
		if err := p.setStatus(ctx, job, domain.JobStatusResultReady, "", ""); err != nil {
			return err
		}
		return p.streams.PublishTo(ctx, redisqueue.StreamDelivery, taskOf(job))

	case domain.ProviderTaskProcessing:
		if err := p.setStatus(ctx, job, domain.JobStatusProviderProcessing, "", ""); err != nil {
			return err
		}
		return p.streams.PublishTo(ctx, redisqueue.StreamProviderPoll, taskOf(job))

	case domain.ProviderTaskPending:
		if err := p.setStatus(ctx, job, domain.JobStatusProviderPending, "", ""); err != nil {
			return err
		}
		return p.streams.PublishTo(ctx, redisqueue.StreamProviderPoll, taskOf(job))

	case domain.ProviderTaskFailed:
		return p.handleFailure(ctx, job, task, res.ErrorClass, res.ErrorMessage)

	case domain.ProviderTaskCancelled:
		// Cancellation may arrive from a non-cancellable state; best effort.
		_ = p.setStatus(ctx, job, domain.JobStatusCancelled, "cancelled", "provider task cancelled")
		return nil
	}
	return nil
}

func (p *processor) probeVideoOutputs(ctx context.Context, job *domain.Job) error {
	if job.Modality != domain.ModalityVideo {
		return nil
	}
	operationLabel := operationMetricLabel(job.OperationType)
	modalityLabel := modalityMetricLabel(job.Modality)
	if err := p.setStatus(ctx, job, domain.JobStatusPostprocessing, "", ""); err != nil {
		return err
	}
	if len(job.OutputArtifactIDs) == 0 {
		metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "video_output_missing")
		return mediaProbeError("video_output_missing")
	}
	if p.videoProber == nil {
		if p.requireVideoProbe {
			if err := p.markVideoProbeFailed(ctx, job); err != nil {
				return err
			}
			metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "media_probe_unavailable")
			return mediaProbeError("media_probe_unavailable")
		}
		return p.markVideoProbeSkipped(ctx, job)
	}
	if p.objects == nil {
		if err := p.markVideoProbeFailed(ctx, job); err != nil {
			return err
		}
		metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "media_probe_storage_unavailable")
		return mediaProbeError("media_probe_storage_unavailable")
	}
	providerName, modelClass, contract, err := p.videoOutputContract(ctx, job)
	if err != nil {
		metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "media_contract_unavailable")
		return mediaProbeError("media_contract_unavailable")
	}

	for _, artID := range job.OutputArtifactIDs {
		art, err := p.artifactRepo.GetByID(ctx, artID)
		if err != nil {
			metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "artifact_metadata_unavailable")
			return mediaProbeError("artifact_metadata_unavailable")
		}
		if art.MediaType != domain.MediaTypeVideo {
			if err := p.markArtifactProbeFailed(ctx, art); err != nil {
				return err
			}
			metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "video_artifact_missing")
			return mediaProbeError("video_artifact_missing")
		}
		data, err := p.objects.GetObject(ctx, art.StorageBucket, art.StorageKey)
		if err != nil {
			if markErr := p.markArtifactProbeFailed(ctx, art); markErr != nil {
				return markErr
			}
			metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "artifact_bytes_unavailable")
			return mediaProbeError("artifact_bytes_unavailable")
		}
		originalSize := art.SizeBytes
		if originalSize <= 0 {
			originalSize = int64(len(data))
		}
		metrics.ObserveMediaBytes(operationLabel, modalityLabel, string(domain.VariantOriginal), originalSize)
		releaseProbe, ok := acquireOptionalLimiter(p.probeLimiter)
		if !ok {
			if markErr := p.markArtifactProbeFailed(ctx, art); markErr != nil {
				return markErr
			}
			metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "media_probe_overloaded")
			return mediaProbeError("media_probe_overloaded")
		}
		metadata, err := p.videoProber.ProbeVideo(ctx, data, art.SizeBytes)
		releaseProbe()
		if err != nil {
			art.ApplyMediaMetadata(metadata)
			art.ProbeStatus = domain.MediaProbeFailed
			art.Status = domain.ArtifactStatusFailed
			if updateErr := p.artifactRepo.Update(ctx, art); updateErr != nil {
				return updateErr
			}
			metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "media_probe_failed")
			return mediaProbeError("media_probe_failed")
		}
		art.ApplyMediaMetadata(metadata)
		art.ProbeStatus = domain.MediaProbePassed
		art.Status = domain.ArtifactStatusReady
		if err := p.artifactRepo.Update(ctx, art); err != nil {
			return err
		}
		metrics.ObserveMediaProbe("success", operationLabel, modalityLabel, "none")
		if p.videoFastPathAllowed(contract, metadata, originalSize) {
			metrics.ObserveMediaVideoFastPath("used", operationLabel, modalityLabel, string(providerName), modelClass)
			continue
		}
		if p.videoTranscodeAllowed(contract) {
			metrics.ObserveMediaVideoFastPath("fallback_transcode", operationLabel, modalityLabel, string(providerName), modelClass)
			if err := p.transcodeVideoVariant(ctx, job, art, data, metadata); err != nil {
				return err
			}
			continue
		}
		if p.localDevRawVideoAllowedWithoutContract(contract) {
			metrics.ObserveMediaVideoFastPath("dev_raw", operationLabel, modalityLabel, string(providerName), modelClass)
			continue
		}
		if err := p.markArtifactProbeFailed(ctx, art); err != nil {
			return err
		}
		metrics.ObserveMediaVideoFastPath("blocked", operationLabel, modalityLabel, string(providerName), modelClass)
		return mediaProbeError("media_contract_output_not_delivery_ready")
	}
	return nil
}

func (p *processor) videoOutputContract(ctx context.Context, job *domain.Job) (domain.ProviderName, string, *domain.ProviderMediaContract, error) {
	if p.providers == nil {
		return "", "unknown", nil, nil
	}
	task, err := p.latestTask(ctx, job.ID)
	if err != nil {
		return "", "unknown", nil, err
	}
	if task == nil {
		return "", "unknown", nil, nil
	}
	modelClass := p.providers.metricModelForTask(task.Provider, task.ModelCode, job.Modality)
	contract, _ := p.providers.videoContractForTask(task.Provider, task.ModelCode)
	if contract != nil && strings.TrimSpace(contract.ModelClass) != "" {
		modelClass = providerMetricModel(contract.ModelClass)
	}
	return task.Provider, modelClass, contract, nil
}

func (p *processor) videoFastPathAllowed(contract *domain.ProviderMediaContract, metadata domain.ArtifactMediaMetadata, sizeBytes int64) bool {
	if !rawVideoPolicyAllowsProbePassed(p.rawVideoPolicy) {
		return false
	}
	return deliveryReadyVideoOutput(contract, metadata, sizeBytes)
}

func (p *processor) videoTranscodeAllowed(contract *domain.ProviderMediaContract) bool {
	if p.videoTranscoder == nil {
		return false
	}
	switch p.videoTranscodePolicy {
	case videoTranscodePolicyFallback, videoTranscodePolicyAlways:
	default:
		return false
	}
	return contract == nil || contract.TranscodeAllowed || contract.RequiresTranscode
}

func (p *processor) localDevRawVideoAllowedWithoutContract(contract *domain.ProviderMediaContract) bool {
	return contract == nil && p.rawVideoPolicy == rawProviderVideoPolicyAlwaysDevOnly
}

func rawVideoPolicyAllowsProbePassed(policy string) bool {
	switch normalizeWorkerPolicy(policy) {
	case rawProviderVideoPolicyIfProbePassed, rawProviderVideoPolicyAlwaysDevOnly:
		return true
	default:
		return false
	}
}

func (p *processor) transcodeVideoVariant(ctx context.Context, job *domain.Job, art *domain.Artifact, data []byte, originalMetadata domain.ArtifactMediaMetadata) error {
	if p.videoTranscoder == nil {
		return nil
	}
	operationLabel := operationMetricLabel(job.OperationType)
	modalityLabel := modalityMetricLabel(job.Modality)
	variantType := string(domain.VariantVKVideo)
	started := time.Now()
	result := "success"
	errorClass := "none"
	releaseVariant, ok := acquireOptionalLimiter(p.variantLimiter)
	if !ok {
		metrics.ObserveMediaTranscode("error", operationLabel, modalityLabel, variantType, "media_variant_backlog_full")
		metrics.ObserveMediaTranscodeDuration("error", operationLabel, modalityLabel, variantType, time.Since(started))
		if err := p.markArtifactProbeFailed(ctx, art); err != nil {
			return err
		}
		return mediaTranscodeError("media_variant_backlog_full")
	}
	defer releaseVariant()
	metrics.AddMediaVariantBacklog(operationLabel, modalityLabel, variantType, 1)
	defer func() {
		metrics.AddMediaVariantBacklog(operationLabel, modalityLabel, variantType, -1)
		metrics.ObserveMediaTranscode(result, operationLabel, modalityLabel, variantType, errorClass)
		metrics.ObserveMediaTranscodeDuration(result, operationLabel, modalityLabel, variantType, time.Since(started))
	}()
	if p.videoProber == nil {
		result = "error"
		errorClass = "variant_probe_unavailable"
		if err := p.markArtifactProbeFailed(ctx, art); err != nil {
			return err
		}
		return mediaTranscodeError("variant_probe_unavailable")
	}
	releaseTranscode, ok := acquireOptionalLimiter(p.transcodeLimiter)
	if !ok {
		result = "error"
		errorClass = "media_transcode_overloaded"
		if err := p.markArtifactProbeFailed(ctx, art); err != nil {
			return err
		}
		return mediaTranscodeError("media_transcode_overloaded")
	}
	variantBytes, expectedMetadata, err := p.videoTranscoder.TranscodeVKVideo(ctx, data, originalMetadata)
	releaseTranscode()
	if err != nil {
		result = "error"
		errorClass = "media_transcode_failed"
		if markErr := p.markArtifactProbeFailed(ctx, art); markErr != nil {
			return markErr
		}
		return mediaTranscodeError("media_transcode_failed")
	}
	metrics.ObserveMediaBytes(operationLabel, modalityLabel, variantType, int64(len(variantBytes)))
	releaseProbe, ok := acquireOptionalLimiter(p.probeLimiter)
	if !ok {
		result = "error"
		errorClass = "variant_probe_overloaded"
		metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "variant_probe_overloaded")
		if markErr := p.markArtifactProbeFailed(ctx, art); markErr != nil {
			return markErr
		}
		return mediaTranscodeError("variant_probe_overloaded")
	}
	variantMetadata, err := p.videoProber.ProbeVideo(ctx, variantBytes, int64(len(variantBytes)))
	releaseProbe()
	if err != nil {
		result = "error"
		errorClass = "variant_probe_failed"
		metrics.ObserveMediaProbe("error", operationLabel, modalityLabel, "variant_probe_failed")
		if markErr := p.markArtifactProbeFailed(ctx, art); markErr != nil {
			return markErr
		}
		return mediaTranscodeError("variant_probe_failed")
	}
	metrics.ObserveMediaProbe("success", operationLabel, modalityLabel, "none")
	if variantMetadata.ProbeStatus == domain.MediaProbeUnknown || variantMetadata.ProbeStatus == "" {
		variantMetadata.ProbeStatus = domain.MediaProbePassed
	}
	if variantMetadata.Codec == "" || variantMetadata.Container == "" {
		merged := expectedMetadata.Normalize()
		if variantMetadata.Codec == "" {
			variantMetadata.Codec = merged.Codec
		}
		if variantMetadata.Container == "" {
			variantMetadata.Container = merged.Container
		}
	}
	if _, err := p.artifacts.SaveVariantWithMetadata(ctx, art, domain.VariantVKVideo, "video/mp4", variantBytes, variantMetadata); err != nil {
		result = "error"
		errorClass = "variant_store_failed"
		if markErr := p.markArtifactProbeFailed(ctx, art); markErr != nil {
			return markErr
		}
		return mediaTranscodeError("variant_store_failed")
	}
	return nil
}

func (p *processor) markVideoProbeSkipped(ctx context.Context, job *domain.Job) error {
	operationLabel := operationMetricLabel(job.OperationType)
	modalityLabel := modalityMetricLabel(job.Modality)
	for _, artID := range job.OutputArtifactIDs {
		art, err := p.artifactRepo.GetByID(ctx, artID)
		if err != nil {
			return err
		}
		if art.MediaType != domain.MediaTypeVideo {
			continue
		}
		art.ApplyMediaMetadata(domain.ArtifactMediaMetadata{ProbeStatus: domain.MediaProbeSkipped})
		art.Status = domain.ArtifactStatusReady
		if err := p.artifactRepo.Update(ctx, art); err != nil {
			return err
		}
		metrics.ObserveMediaProbe("skipped", operationLabel, modalityLabel, "none")
	}
	return nil
}

func (p *processor) markVideoProbeFailed(ctx context.Context, job *domain.Job) error {
	for _, artID := range job.OutputArtifactIDs {
		art, err := p.artifactRepo.GetByID(ctx, artID)
		if err != nil {
			return err
		}
		if err := p.markArtifactProbeFailed(ctx, art); err != nil {
			return err
		}
	}
	return nil
}

func (p *processor) markArtifactProbeFailed(ctx context.Context, art *domain.Artifact) error {
	art.ApplyMediaMetadata(domain.ArtifactMediaMetadata{ProbeStatus: domain.MediaProbeFailed})
	art.Status = domain.ArtifactStatusFailed
	return p.artifactRepo.Update(ctx, art)
}

func (p *processor) handleMediaFailure(ctx context.Context, job *domain.Job, errorCode, message string) error {
	if releaseErr := p.releaseReserved(ctx, job); releaseErr != nil {
		return releaseErr
	}
	metrics.JobsTerminal.WithLabelValues(string(domain.JobStatusFailedTerminal)).Inc()
	return p.setStatus(ctx, job, domain.JobStatusFailedTerminal, errorCode, message)
}

type mediaProbeError string

func (e mediaProbeError) Error() string {
	if e == "" {
		return "media_probe_failed"
	}
	return string(e)
}

type mediaTranscodeError string

func (e mediaTranscodeError) Error() string {
	if e == "" {
		return "media_transcode_failed"
	}
	return string(e)
}

func safeMediaFailureCode(err error) string {
	var probeErr mediaProbeError
	if errors.As(err, &probeErr) {
		switch string(probeErr) {
		case "media_probe_overloaded":
			return domain.JobErrMediaOverloadedRetryLater
		case "media_probe_unavailable",
			"media_probe_storage_unavailable",
			"media_contract_unavailable",
			"artifact_metadata_unavailable",
			"artifact_bytes_unavailable":
			return domain.JobErrMediaProcessingUnavailable
		default:
			return domain.JobErrMediaProviderOutputInvalid
		}
	}
	var transcodeErr mediaTranscodeError
	if errors.As(err, &transcodeErr) {
		switch string(transcodeErr) {
		case "media_transcode_overloaded",
			"variant_probe_overloaded",
			"media_variant_backlog_full":
			return domain.JobErrMediaOverloadedRetryLater
		default:
			return domain.JobErrMediaProcessingUnavailable
		}
	}
	return domain.JobErrMediaProcessingUnavailable
}

func safeMediaFailureMessage(err error) string {
	switch safeMediaFailureCode(err) {
	case domain.JobErrMediaProviderOutputInvalid:
		return "generated media failed safety checks; credits were not charged"
	case domain.JobErrMediaOverloadedRetryLater:
		return "media processing is overloaded; credits were not charged"
	default:
		return "media processing is unavailable; credits were not charged"
	}
}

func (p *processor) saveDialogAnswer(ctx context.Context, job *domain.Job, answer string) error {
	if p.textContext == nil || answer == "" || job.OperationType != domain.OperationTextGenerate || job.Modality != domain.ModalityText {
		return nil
	}
	var pp promptParams
	if len(job.Params) > 0 {
		_ = json.Unmarshal(job.Params, &pp)
	}
	if pp.ConversationID == "" {
		return nil
	}
	conversationID, err := uuid.Parse(pp.ConversationID)
	if err != nil {
		return nil
	}
	return p.textContext.Complete(ctx, job, conversationID, answer)
}

// saveOutputs stores each provider output URL as an output artifact and records
// the artifact ids on the job, skipping ids already attached (idempotent).
func (p *processor) saveOutputs(ctx context.Context, job *domain.Job, urls []string) error {
	ctx, span := tracing.Start(ctx, "artifact.save_outputs",
		attribute.String("job.id", job.ID.String()),
		attribute.String("modality", string(job.Modality)),
		attribute.Int("artifact.output_count", len(urls)),
		tracing.CorrelationAttr(job.CorrelationID),
	)
	defer span.End()

	mediaType := mediaTypeFor(job.Modality)
	for _, url := range urls {
		art, err := p.artifacts.SaveRemoteArtifact(ctx, job.UserID, &job.ID, domain.ArtifactKindOutput, mediaType, url)
		if err != nil {
			tracing.RecordError(span, err)
			return err
		}
		if !containsID(job.OutputArtifactIDs, art.ID) {
			job.OutputArtifactIDs = append(job.OutputArtifactIDs, art.ID)
		}
	}
	if err := p.jobs.Update(ctx, job); err != nil {
		tracing.RecordError(span, err)
		return err
	}
	return nil
}

// handleFailure classifies a provider failure and either re-queues the job for
// another attempt (with backoff) or, once the retry budget is exhausted (or the
// error is non-retryable), dead-letters the task and moves the job to a terminal
// failed state. The budget spans every phase (submit, poll, download): it is the
// max of the provider-task count and the task's own re-enqueue counter, so a
// failure that does not create a new provider task (e.g. output_download_failed)
// can no longer loop forever.
func (p *processor) handleFailure(ctx context.Context, job *domain.Job, task queue.Task, class domain.ProviderErrorClass, msg string) error {
	code := string(class)

	// If a provider task was running, record the provider_failed state first.
	switch job.Status {
	case domain.JobStatusProviderSubmitted, domain.JobStatusProviderPending, domain.JobStatusProviderProcessing:
		_ = p.setStatus(ctx, job, domain.JobStatusProviderFailed, code, msg)
	}

	providerAttempts, err := p.attemptCount(ctx, job.ID)
	if err != nil {
		return err
	}
	attempts := providerAttempts
	if task.Attempt+1 > attempts {
		attempts = task.Attempt + 1
	}

	if isRetryable(class) && attempts < p.maxAttempts {
		if err := p.setStatus(ctx, job, domain.JobStatusFailedRetryable, code, msg); err != nil {
			return err
		}
		if err := p.setStatus(ctx, job, domain.JobStatusQueued, code, msg); err != nil {
			return err
		}
		next := task
		next.Attempt = task.Attempt + 1
		p.sleepBackoff(ctx, next.Attempt)
		return p.streams.PublishTo(ctx, redisqueue.StreamForOperation(job.OperationType), next)
	}

	// Budget exhausted (retryable) or non-retryable: dead-letter retryable
	// failures for inspection, then move the job to a terminal state.
	if err := p.releaseReserved(ctx, job); err != nil {
		return err
	}
	if isRetryable(class) {
		p.toDLQ(ctx, task, code, msg)
	}
	metrics.JobsTerminal.WithLabelValues(string(domain.JobStatusFailedTerminal)).Inc()
	terminalCode, terminalMessage := safeTerminalFailure(job, class)
	if err := p.setStatus(ctx, job, domain.JobStatusFailedTerminal, terminalCode, terminalMessage); err != nil {
		return err
	}
	if p.shouldNotifyTerminalProviderFailure(job) {
		return p.streams.PublishTo(ctx, redisqueue.StreamDelivery, taskOf(job))
	}
	return nil
}

func safeTerminalFailure(job *domain.Job, class domain.ProviderErrorClass) (string, string) {
	if job != nil && (job.Modality == domain.ModalityImage || job.Modality == domain.ModalityVideo) {
		switch class {
		case domain.ProviderErrRateLimited, domain.ProviderErrOverloaded, domain.ProviderErrTimeout:
			return domain.JobErrMediaOverloadedRetryLater, "media generation is temporarily overloaded; credits were not charged"
		case domain.ProviderErrOutputDownloadFailed:
			return domain.JobErrMediaProcessingUnavailable, "media output could not be loaded safely; credits were not charged"
		case domain.ProviderErrMediaProbeFailed:
			return domain.JobErrMediaProviderOutputInvalid, "generated media failed safety checks; credits were not charged"
		case domain.ProviderErrMediaTranscodeFailed:
			return domain.JobErrMediaProcessingUnavailable, "media processing is unavailable; credits were not charged"
		}
	}
	return string(class), safeProviderFailureMessage(class)
}

func safeProviderFailureMessage(class domain.ProviderErrorClass) string {
	switch class {
	case domain.ProviderErrRateLimited, domain.ProviderErrOverloaded, domain.ProviderErrTimeout:
		return "provider is temporarily unavailable; credits were not charged"
	case domain.ProviderErrContentRejected:
		return "content was rejected by safety policy; credits were not charged"
	case domain.ProviderErrInvalidRequest, domain.ProviderErrUnsupportedCapab:
		return "request is not supported; credits were not charged"
	case domain.ProviderErrAuthFailed, domain.ProviderErrInsufficientBalance:
		return "provider configuration is unavailable; credits were not charged"
	default:
		return "generation failed; credits were not charged"
	}
}

func (p *processor) releaseReserved(ctx context.Context, job *domain.Job) error {
	if p.releaser == nil || job.CostReserved <= 0 || job.CostCaptured > 0 {
		return nil
	}
	if err := p.releaser.ReleaseForJob(ctx, job.ID); err != nil {
		metrics.BillingReleases.WithLabelValues(operationMetricLabel(job.OperationType), "error").Inc()
		return err
	}
	metrics.BillingReleases.WithLabelValues(operationMetricLabel(job.OperationType), "success").Inc()
	return nil
}

func (p *processor) shouldNotifyTerminalProviderFailure(job *domain.Job) bool {
	return p.streams != nil && job.VKPeerID != 0 && (job.Modality == domain.ModalityImage || job.Modality == domain.ModalityVideo)
}

// moderateOutput runs the output moderation check and, on a block, rejects the
// job (no delivery, no capture), releases the reservation and records an audit
// verdict. It returns blocked=true when delivery must be stopped. When no
// moderator is configured it is a no-op (allow).
func (p *processor) moderateOutput(ctx context.Context, job *domain.Job) (bool, error) {
	if p.moderator == nil {
		return false, nil
	}
	ctx, span := tracing.Start(ctx, "moderation.output",
		attribute.String("job.id", job.ID.String()),
		attribute.String("modality", string(job.Modality)),
		tracing.CorrelationAttr(job.CorrelationID),
	)
	defer span.End()

	var pp promptParams
	if len(job.Params) > 0 {
		_ = json.Unmarshal(job.Params, &pp)
	}
	out, err := p.moderator.Check(ctx, moderationservice.Input{
		Stage:    domain.ModerationStageOutput,
		Modality: job.Modality,
		Prompt:   pp.Prompt,
	})
	if err != nil {
		tracing.RecordError(span, err)
		return false, err
	}
	span.SetAttributes(attribute.String("moderation.decision", string(out.Decision)))

	if p.modResults != nil {
		var artID *uuid.UUID
		if len(job.OutputArtifactIDs) > 0 {
			id := job.OutputArtifactIDs[0]
			artID = &id
		}
		_ = p.modResults.Create(ctx, &domain.ModerationResult{
			JobID:      job.ID,
			ArtifactID: artID,
			Stage:      domain.ModerationStageOutput,
			Decision:   out.Decision,
			Categories: out.Categories,
			Provider:   p.moderator.Name(),
		})
	}

	metrics.ModerationDecisions.WithLabelValues(string(out.Decision)).Inc()
	if out.Decision.Allowed() {
		return false, nil
	}

	if err := p.setStatus(ctx, job, domain.JobStatusRejected, "content_rejected", "blocked by output moderation"); err != nil {
		tracing.RecordError(span, err)
		return false, err
	}
	metrics.JobsTerminal.WithLabelValues(string(domain.JobStatusRejected)).Inc()
	if p.releaser != nil {
		if err := p.releaser.ReleaseForJob(ctx, job.ID); err != nil {
			metrics.BillingReleases.WithLabelValues(operationMetricLabel(job.OperationType), "error").Inc()
			tracing.RecordError(span, err)
			return false, err
		}
		metrics.BillingReleases.WithLabelValues(operationMetricLabel(job.OperationType), "success").Inc()
	}
	return true, nil
}

// toDLQ publishes the exhausted task to the dead-letter stream. It is best
// effort: a DLQ publish failure must not block moving the job to terminal.
func (p *processor) toDLQ(ctx context.Context, task queue.Task, code, msg string) {
	metrics.DLQRouted.WithLabelValues("provider").Inc()
	_ = p.streams.PublishTo(ctx, redisqueue.StreamDLQ, task)
	_ = code
	_ = msg
}

// sleepBackoff waits for the configured backoff before a re-enqueue, honoring
// context cancellation.
func (p *processor) sleepBackoff(ctx context.Context, attempt int) {
	d := p.backoff(attempt)
	if d <= 0 {
		return
	}
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
	case <-t.C:
	}
}

func (p *processor) attemptCount(ctx context.Context, jobID uuid.UUID) (int, error) {
	tasks, err := p.tasks.ListByJob(ctx, jobID)
	if err != nil {
		return 0, err
	}
	return len(tasks), nil
}

func containsID(ids []uuid.UUID, id uuid.UUID) bool {
	for _, x := range ids {
		if x == id {
			return true
		}
	}
	return false
}
