package domain

import (
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
)

// ConversationSource identifies the app surface that owns a dialog thread.
type ConversationSource string

const (
	ConversationSourceVKBot   ConversationSource = "vk_bot"
	ConversationSourceMiniApp ConversationSource = "miniapp"
	ConversationSourceWeb     ConversationSource = "web"
)

// ErrConversationAccountOwnershipRequired is returned when a web conversation
// lacks the canonical account owner required for account-native access.
var ErrConversationAccountOwnershipRequired = errors.New("domain: conversation account ownership required")

// ConversationStatus describes whether a dialog thread can receive new
// messages. VK bot context uses one active conversation per user/peer.
type ConversationStatus string

const (
	ConversationActive   ConversationStatus = "active"
	ConversationArchived ConversationStatus = "archived"
)

// ConversationTitleOrigin records who last established the durable title.
// It is internal metadata and is deliberately excluded from public DTOs.
type ConversationTitleOrigin string

const (
	ConversationTitleOriginManual        ConversationTitleOrigin = "manual"
	ConversationTitleOriginAutoPending   ConversationTitleOrigin = "auto_pending"
	ConversationTitleOriginAutoFallback  ConversationTitleOrigin = "auto_fallback"
	ConversationTitleOriginAutoGenerated ConversationTitleOrigin = "auto_generated"
)

// Conversation is the server-side memory thread used to build compact text
// model context. It is not sent to providers directly; workers render a bounded
// prompt from its messages and summary.
type Conversation struct {
	ID               uuid.UUID               `json:"id"`
	UserID           uuid.UUID               `json:"user_id"`
	AccountID        uuid.UUID               `json:"account_id,omitempty"`
	Source           ConversationSource      `json:"source"`
	VKPeerID         int64                   `json:"vk_peer_id"`
	ExternalThreadID string                  `json:"external_thread_id,omitempty"`
	Status           ConversationStatus      `json:"status"`
	Title            string                  `json:"title,omitempty"`
	TitleOrigin      ConversationTitleOrigin `json:"-"`
	CreatedAt        time.Time               `json:"created_at"`
	UpdatedAt        time.Time               `json:"updated_at"`
}

// NormalizeTitleOrigin applies safe defaults for legacy records. Only blank
// newly-created Web conversations are eligible for automatic title work;
// every other source or pre-named conversation is manual by default.
func (c *Conversation) NormalizeTitleOrigin() {
	if c == nil {
		return
	}
	if c.Source != ConversationSourceWeb {
		c.TitleOrigin = ConversationTitleOriginManual
		return
	}
	switch c.TitleOrigin {
	case ConversationTitleOriginManual,
		ConversationTitleOriginAutoPending,
		ConversationTitleOriginAutoFallback,
		ConversationTitleOriginAutoGenerated:
		return
	default:
		if strings.TrimSpace(c.Title) == "" {
			c.TitleOrigin = ConversationTitleOriginAutoPending
			return
		}
		c.TitleOrigin = ConversationTitleOriginManual
	}
}

// ValidateOwnership verifies source-specific ownership invariants before a
// conversation reaches storage.
func (c Conversation) ValidateOwnership() error {
	if c.Source == ConversationSourceWeb && c.AccountID == uuid.Nil {
		return ErrConversationAccountOwnershipRequired
	}
	return nil
}

// ConversationRef is a stable lookup key for an active conversation. VK bot
// uses VKPeerID; Mini App uses ExternalThreadID scoped by backend UserID.
type ConversationRef struct {
	UserID           uuid.UUID
	AccountID        uuid.UUID
	Source           ConversationSource
	VKPeerID         int64
	ExternalThreadID string
}

// ConversationMessageRole is the author role stored in conversation history.
type ConversationMessageRole string

const (
	ConversationRoleUser      ConversationMessageRole = "user"
	ConversationRoleAssistant ConversationMessageRole = "assistant"
)

// ConversationMessageRating is an account holder's durable evaluation of an
// assistant message. The empty value means that no evaluation is stored.
type ConversationMessageRating string

const (
	ConversationMessageRatingNone    ConversationMessageRating = ""
	ConversationMessageRatingLike    ConversationMessageRating = "like"
	ConversationMessageRatingDislike ConversationMessageRating = "dislike"
)

// ErrInvalidConversationMessageRating rejects values outside the public
// like/dislike/clear contract.
var ErrInvalidConversationMessageRating = errors.New("domain: invalid conversation message rating")

// Valid reports whether the value can be persisted.
func (r ConversationMessageRating) Valid() bool {
	return r == ConversationMessageRatingNone || r == ConversationMessageRatingLike || r == ConversationMessageRatingDislike
}

// ConversationMessage is one persisted user/assistant turn in a conversation.
type ConversationMessage struct {
	ID             uuid.UUID                 `json:"id"`
	ConversationID uuid.UUID                 `json:"conversation_id"`
	JobID          uuid.UUID                 `json:"job_id"`
	Seq            int64                     `json:"seq"`
	Role           ConversationMessageRole   `json:"role"`
	Text           string                    `json:"text"`
	Rating         ConversationMessageRating `json:"rating,omitempty"`
	TokenCount     int                       `json:"token_count"`
	CreatedAt      time.Time                 `json:"created_at"`
}

// ConversationSummary is the compact memory of older turns up to
// SummarizedUntilSeq. Newer turns are still included as recent messages.
type ConversationSummary struct {
	ID                 uuid.UUID `json:"id"`
	ConversationID     uuid.UUID `json:"conversation_id"`
	Text               string    `json:"text"`
	TokenCount         int       `json:"token_count"`
	SummarizedUntilSeq int64     `json:"summarized_until_seq"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}
